# Form implementation generated from reading ui file 'D:\Data\uel\HK6\ML\Projects\ML_K23416\studentmanagement-0110\studentmanagement-0110'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


